baseURL: /
languageCode: en-US
defaultContentLanguage: en
title: NBA Project
theme: hugo-theme-learn
metaDataFormat: yaml
defaultContentLanguageInSubdir: yes
params:
  author: Frank Dreyer, Kolja GÃ¼nther, Jannik Greif
  customMermaidURL: https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  description: DataSciR Project Documentation
  disableBreadcrumb: no
  disableSearch: yes
  showVisitedLinks: no
  disableLandingPageButton: no
  disableMermaid: yes
  disableNextPrev: no
  titleSeparator: ':'
  themeVariant: "mine"
outputs:
  home:
    - HTML
    - RSS
    - JSON
Languages:
  en:
    landingPageName: <i class='fas fa-home'></i> Home
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> GitHub repo
          url: https://github.com/jannikgreif/DataSciR_2021
          weight: 10
        - identifier: pn
          name: <i class="fas fa-file"></i> Project notebook
          url: https://github.com/jannikgreif/DataSciR_2021/blob/main/Project_Notebook/project_notebook_with_code.html
          weight: 20          
        - identifier: ps
          name: <i class='fa fa-university'></i> Course website
          url: https://brain.cs.uni-magdeburg.de/kmd/DataSciR/
          weight: 30
